table mc_detente_chien
	lineageTag: 8085db2a-b9a6-4157-820d-8a7322e668c3

	column id
		dataType: int64
		formatString: 0
		lineageTag: 131ff629-2aee-4dc4-8806-30ce4a65dea6
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column heure
		dataType: dateTime
		formatString: Long Time
		lineageTag: 58f2e007-e09d-471b-bf5a-81f3c74d472e
		summarizeBy: none
		sourceColumn: heure

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column duree_detente
		dataType: int64
		formatString: 0
		lineageTag: c01c9422-bb56-4e49-8020-0dadbb81c099
		summarizeBy: sum
		sourceColumn: duree_detente

		annotation SummarizationSetBy = Automatic

	column mc_main_courante_id
		dataType: int64
		formatString: 0
		lineageTag: b4ba6495-40bc-445b-ab91-459092804a34
		summarizeBy: none
		sourceColumn: mc_main_courante_id

		annotation SummarizationSetBy = Automatic

	partition mc_detente_chien = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\mdolm\Downloads\mc_detente_chien.csv"),[Delimiter=";", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"id", Int64.Type}, {"heure", type time}, {"duree_detente", Int64.Type}, {"mc_main_courante_id", Int64.Type}})
				in
				    #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

