table ref_type_resultat_exercice
	lineageTag: c38dc583-3ef5-4920-b106-93411603c8d1

	column id
		dataType: int64
		formatString: 0
		lineageTag: 6506d9c5-1599-44fc-91de-8ed961ce3cfd
		summarizeBy: none
		sourceColumn: id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column nom
		dataType: string
		lineageTag: c159c53f-5d79-4668-a915-42e8cc676f26
		summarizeBy: none
		sourceColumn: nom

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition ref_type_resultat_exercice = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\mdolm\Downloads\ref_type_resultat_exercice.csv"),[Delimiter=";", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"id", Int64.Type}, {"nom", type text}})
				in
				    #"Type modifié"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

