table ref_cause_annulation_intervention
	lineageTag: d944f991-d927-4f75-9eb9-3de5f2ce2ef7

	column id
		dataType: int64
		formatString: 0
		lineageTag: 7597558e-e73f-47f7-928b-e2339d617b47
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column nom
		dataType: string
		lineageTag: 337f6a28-f5cf-4326-8e5d-37791c4c5ed2
		summarizeBy: none
		sourceColumn: nom

		annotation SummarizationSetBy = Automatic

	partition ref_cause_annulation_intervention = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\mdolm\Downloads\ref_cause_annulation_intervention.csv"),[Delimiter=";", Columns=2, Encoding=65001]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"id", Int64.Type}, {"nom", type text}})
				in
				    #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

