table roles
	lineageTag: bad61d0d-6dc7-4af2-a7f7-2c50432dd799

	column id
		dataType: int64
		formatString: 0
		lineageTag: 27976ee7-eb13-43c6-a2ac-c0f9b68d62f2
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: d0daae3a-bd6f-4862-8d1e-76cddc970baa
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	partition roles = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\mdolm\Downloads\roles.csv"),[Delimiter=";", Columns=2, Encoding=65001]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"id", Int64.Type}, {"name", type text}})
				in
				    #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

