table stations
	lineageTag: 81ce65a7-a84d-4164-9472-608ba457b83a

	column id
		dataType: int64
		formatString: 0
		lineageTag: 587b9d6d-22d8-4275-aed4-751f8debbe4e
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: afe72a25-28af-46a9-bd56-4d2d75b5d28d
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	partition stations = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\mdolm\Downloads\stations.csv"),[Delimiter=";", Columns=2, Encoding=65001]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"id", Int64.Type}, {"name", type text}})
				in
				    #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

